### ISSUE TITLE
ONBUILD vs Volumes

### ISSUE THREAD

**Issue by dnephin** [andyshinn/docker-alpine-abuild#2]
Hello,

I just discovered this repo after having built something similar a few weeks ago:
https://github.com/dnephin/docker-apk-build

While they accomplish the same goal, we took very different approaches.  The main difference seems to be the use of `ONBUILD` vs using volumes.

It seems like with ONBUILD, to build a package you end up with something like this:

```
# Create a new Dockerfile to trigger `ONBUILD`
# Copy your packaging keys into place
docker build -t alpine-abuild .
docker run --name package alpine-abuild
docker cp ...
docker rm package
```

While I was using this to try and build `alpine-pkg-glibc` I noticed the version it's pulling from arch is no longer available, so I update the version.  Now I need run checksum again, and ended up having to use volumes anyway.

The main disadvantage I can see to using volumes is that it requires some scripting on the host side (currently in https://github.com/dnephin/docker-apk-build/blob/master/Makefile, but I am planning on pulling it out into a bash script so that parts can be parameterized), or having to type a much longer `docker run` command.

The advantage to using volumes is that it removes the need for most of the steps. It becomes:

```
docker build -t alpine-abuild .
docker run --rm -v $PWD:/work-v keys:/home/packager/.abuild alpine-abuild
```

and the image can be used interactively if you're having to trial/error a new package with lots of dependencies. There is no need to create a new Dockerfile for each repo.

Thoughts? Do you think the tradeoff of not having to run a script on the host (to setup volumes) is worth the extra steps to use the image in different ways (build, test, interactive), and having to copy keys around.

**Comment by andyshinn** [comment]
Actually, I was going to refactor this to use environment variables and volumes. See my example in https://github.com/andyshinn/docker-alpine-abuild/tree/refactor_env_volumes. Then, you only need the volume for the package data and the key is left out of the image.

**Comment by andyshinn** [comment]
I pushed a new image which uses environment for the keys and volumes for the package. You can see the changes in the `README.md`. It makes it a little easier to keep `Dockerfile` stuff out of packages.
