### ISSUE TITLE
Value for RSA_PRIVATE_KEY_NAME is required

### ISSUE THREAD

**Issue by sgerrand** [andyshinn/docker-alpine-abuild#4]
The value of the environment variable `RSA_PRIVATE_KEY_NAME` is a required value in `abuilder`, which is not articulated in the README. If a value for this is not provided, the `abuilder` script explodes at runtime with an opaque error message:

```
/bin/abuilder: line 15: can't create /home/builder/: Is a directory
```

This error is due to 94f1a50fd3869de46c7dbf95a600bca57368fa98 and is caused by https://github.com/andyshinn/docker-alpine-abuild/blob/94f1a50fd3869de46c7dbf95a600bca57368fa98/abuilder#L8

``` bash
echo -e "$RSA_PRIVATE_KEY" > "/home/builder/$RSA_PRIVATE_KEY_NAME"
```

:thought_balloon: It would be more convenient for this environment variable to be optional and have a sensible default provided, which can then be overridden at runtime.

**Comment by andyshinn** [comment]
Yea, I'll find a better way to make this optional.

**Comment by sgerrand** [comment]
:wave: @andyshinn: There's a changeset in #6 which addresses this. Let me know what you think.
