### ISSUE TITLE
building node.js failed

### ISSUE THREAD

**Issue by zanhsieh** [andyshinn/docker-alpine-abuild#9]
Hi,

Thanks for providing such wonderful tool for building Alpine linux apk. I, however, tried to build node.js 6.6.0 and run into this problem:

```
$ docker run \
>     -e RSA_PRIVATE_KEY="$(cat ~/.abuild/zanhsieh@gmail.com-57e1dd44.rsa)" \
>     -e RSA_PRIVATE_KEY_NAME="zanhsieh@gmail.com-57e1dd44.rsa" \
>     -v "$PWD:/home/builder/package" \
>     -v "$HOME/.abuild/packages:/packages" \
>     -v "$HOME/.abuild/zanhsieh@gmail.com-57e1dd44.rsa.pub:/etc/apk/keys/zanhsieh@gmail.com-57e1dd44.rsa.pub" \
>     andyshinn/alpine-abuild:edge
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
...
  LINK(target) /home/builder/package/src/node-v6.6.0/out/Release/mksnapshot
make: Leaving directory '/home/builder/package/src/node-v6.6.0/out'
attr_set: Not supported
Could not set "pax.flags" for out/Release/mksnapshot
>>> ERROR: nodejs: all failed
>>> nodejs: Uninstalling dependencies...
```

The APKBUILD I took is from [official alpine linux git](http://git.alpinelinux.org/cgit/aports/plain/main/nodejs/APKBUILD). 

My docker info:

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 136
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 237
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: moby
ID: 67OI:VNUT:3VMC:PTRS:FRG2:SY3N:CJYP:TWBC:DKKP:E4WQ:BKKZ:LVPS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 29
 System Time: 2016-09-21T06:04:26.410040411Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: zanhsieh
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

The host system is Mac OSX El Capitan 10.11.6 (MBP early 2015) with 8GB RAM 120GB SSD HDD. 

Did I do something wrong?

**UPDATE**: I have borrow a Dell laptop with Ubuntu 14.04. After tweaking around (e.g. `sudo mkdir -p ~/.abuild/packages/builder/x86_64 && sudo chown <uid>:<ugroup> -R ~/.abuild/packages`), it seems not happen in Ubuntu 14.04. I guess may be something to do with AUFS and/or xhype.

**Comment by andyshinn** [comment]
This is likely because the builder is trying to set `pax.flags` on a file that is mapped to the Mac host and isn't supported. I think abuild supports a different location for the src directory (maybe something outside the mount like `/tmp/src` would work).

**Comment by zanhsieh** [comment]
@andyshinn Tested with mounting to /tmp/nodejs_alpine as build.sh (Mac OSX), not working. Same error. 

```
#!/usr/bin/env bash
#
# build.sh
# 
MY_KEY_ID="zanhsieh@gmail.com-57e1dd44"
TARGET_DIR="/tmp/nodejs"
TMP_DIR="/tmp/packages"

mkdir -p $TMP_DIR/builder/x86_64
mkdir -p $TARGET_DIR

[ ! -f $TARGET_DIR/APKBUILD ] &&  wget -P $TARGET_DIR http://git.alpinelinux.org/cgit/aports/plain/main/nodejs/APKBUILD

cd $TARGET_DIR
docker run \
    -e RSA_PRIVATE_KEY="`cat ~/.abuild/$MY_KEY_ID.rsa`" \
    -e RSA_PRIVATE_KEY_NAME="$MY_KEY_ID.rsa" \
    -v "$TARGET_DIR:/home/builder/package" \
    -v "$TMP_DIR:/packages" \
    -v "$HOME/.abuild/$MY_KEY_ID.rsa.pub:/etc/apk/keys/$MY_KEY_ID.rsa.pub" \
    andyshinn/alpine-abuild:edge
cd -
```

So the end result I probably would stick on some Virtualbox Linux VM.

**Comment by pracucci** [comment]
FYI, I had the same problem and I've successfully built NodeJS just picking the original `APKBUILD` + patch files, and adding the following to the `APKBUILD` so that the building occurs outside the mount from OSX:

```
srcdir="/tmp/build"
pkgbasedir="$srcdir/node-v${pkgver}-pkg"
```

**Comment by hernandev** [comment]
Hey guys, having the same issue, but mine are on the `pkg` directory, gonna try a "pkgdir" variable to see if it solves, otherwise it's making me wanna cry cause the build takes long to see the error only at the end. :)

**Comment by hernandev** [comment]
@pracucci tip worked like a charm! thank you man!
